import os
import json
from typing import Any, Dict, List
import requests
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_API_BASE = os.getenv("OPENAI_API_BASE", "https://api.openai.com/v1")
MODEL_NAME = os.getenv("OPENAI_MODEL", "gpt-4.1")

if not OPENAI_API_KEY:
    raise RuntimeError("OPENAI_API_KEY is not set")


# 1. Define a list of callable tools for the model (Chat Completions format)
tools: List[Dict[str, Any]] = [
    {
        "type": "function",
        "function": {
            "name": "grep",
            "description": "Search text with an advanced grep-like matcher and return formatted results.",
            "parameters": {
                "type": "object",
                "properties": {
                    "pattern": {
                        "type": "string",
                        "description": "A regex (or literal) pattern to search for.",
                    }
                },
                "required": ["pattern"],
            },
        },
    }
]


def grep(pattern: str) -> str:
    return f"I will grep the text for the pattern {pattern}"


def post_chat_completions(payload: Dict[str, Any]) -> Dict[str, Any]:
    url = f"{OPENAI_API_BASE}/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENAI_API_KEY}",
        "Content-Type": "application/json",
    }
    response = requests.post(url, headers=headers, json=payload, timeout=60)
    response.raise_for_status()
    return response.json()


# Create a running message list we will add to over time
messages: List[Dict[str, Any]] = [
    {"role": "user", "content": "I will grep the text for the pattern 'software engineer'"}
]

# 2. Prompt the model with tools defined using raw HTTP request
first_payload: Dict[str, Any] = {
    "model": MODEL_NAME,
    "messages": messages,
    "tools": tools,
    "tool_choice": "auto",
}

first_completion = post_chat_completions(first_payload)

# 3. If the model requested tool calls, execute them and add results
choice = first_completion.get("choices", [{}])[0]
assistant_message: Dict[str, Any] = choice.get("message", {})
tool_calls = assistant_message.get("tool_calls") or []

if tool_calls:
    messages.append(
        {
            "role": "assistant",
            "content": assistant_message.get("content") or "",
            "tool_calls": tool_calls,
        }
    )

    for tc in tool_calls:
        function = (tc or {}).get("function") or {}
        name = function.get("name")
        if name == "grep":
            try:
                args = json.loads(function.get("arguments") or "{}")
            except json.JSONDecodeError:
                args = {}
            pattern = args.get("pattern", "")
            grep_result = grep(pattern)
            messages.append(
                {
                    "role": "tool",
                    "tool_call_id": tc.get("id"),
                    "content": grep_result,
                }
            )
else:
    messages.append({"role": "assistant", "content": assistant_message.get("content") or ""})

print("Final input:")
print(messages)

# 4. Ask the model to produce the final answer
messages.append({"role": "system", "content": "Respond only with a grep generated by a tool."})

final_payload: Dict[str, Any] = {
    "model": MODEL_NAME,
    "messages": messages,
    "tools": tools,
}

final_completion = post_chat_completions(final_payload)

# 5. The model should be able to give a response!
print("Final output:")
final_message = (final_completion.get("choices", [{}])[0]).get("message", {})
print(final_message.get("content") or "")